baseURL = 'https://words4.org/'
languageCode = 'en-us'
title = 'Words4'
sectionPagesMenu = 'main'

[params]
  title = "Words4"
  description = "Words4 website"

  organizationId = "Words4 Inc"
  nonprofitStatus = "501(c)(3) Nonprofit Organization"
  taxId = "85-2284025"

[menus]
  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 10
  [[menus.main]]
    name = "Partners"
    pageRef = "/partners"
    weight = 30

[taxonomies]
  tag = "tags"
  category = "categories"
